### ISSUE TITLE
shiny appDir ERROR

### ISSUE THREAD

**Issue by semmrich** [supatt-lab/SingCellaR-myelofibrosis#1]
Hi,
I just read your most recent paper in Molecular CELL and I am deelpy impressed about both data/findings and the underlying bioinformatics you implemented. I am working on comparing hematopoietic hierarchies and would like to use the HEALTHY donor dataset in my study.

I copied the unpacked "projects" folder into the main package library
`getwd()
[1] "C:/Program Files/R/R-3.6.3/library/projects"` 
then I run`
> library(shiny)
> 
> runApp()`

and get this:
`Error in shinyAppDir(x) : App dir must contain either app.R or server.R.`
What's wrong?
Also, I noticed the 
> Psaila_et_al.rdata

S4 class probably contains the cleaned data. Is there any way to convert to SingleCellExperiment class or Seurat class, or extract count matrix for 10X data along with a metadata frame containing your papers cell typing, healthy vs MF sample denominators and the FDG coords?

`
sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_1.4.0.2

loaded via a namespace (and not attached):
 [1] compiler_3.6.3  fastmap_1.0.1   magrittr_1.5    R6_2.4.1        promises_1.1.0  later_1.0.0     htmltools_0.4.0 tools_3.6.3    
 [9] Rcpp_1.0.4.6    digest_0.6.25   xtable_1.8-5    httpuv_1.5.2    mime_0.9.1      rlang_0.4.5    
`

Thanks in advance,
St

-------------------------------------------------------
Stephan Emmrich, PhD
Department of Biology
University of Rochester
213 Hutchison Hall, River Campus
Rochester, NY 14627
USA
phone: +1-585-275-6637
email: stephan.emmrich@rochester.edu

**Comment by supatt-lab** [comment]
Hi Stephan,

It seems like it couldn't find server.R. Did you download the App from my
github?.
BW,
Supat

**Comment by semmrich** [comment]
Hi Supat,
I downloaded the archive from this link:
http://sara.molbiol.ox.ac.uk/public/supatt/shared_data/projects.tar.gz
All R packages mentioned in your github page are already in my library.
And then I copied the unpacked "projects" folder into my R library folder. No idea whats wrong here...
Thanks for your help,
Stephan
________________________________

**Comment by supatt-lab** [comment]
I am wondering. Have you clone or download the Shiny App?. You have to
clone or donwload this githhub
https://github.com/supatt-lab/SingCellaR-myelofibrosis.
The link i have provided is for the data NOT the Shiny App.

**Comment by semmrich** [comment]
Perfect, That solved it! All contents are accessible. Sorry, my mistake, should've checked this more carefully. Thank you for your quick help, kudos
