### ISSUE TITLE
app not running as shiny web-app

### ISSUE THREAD

**Issue by splaisan** [supatt-lab/SingCellaR-myelofibrosis#2]
Thanks for the great app

I get the following error message in my browser when I try to start the shiny standalone app 
**http://XX.XX.XX.XX:3838/shinyapps/SingCellaR-myelofibrosis/:**

```
An error has occurred
The application failed to start.

The application exited during initialization.
```

I can use it when I run it manually from RStudio server on the same server but not as a standalone shiny app.
Is there a way to tune it so that it starts there as well?

Thanks

REM: content of the log file

```
cat SingCellaR-myelofibrosis-20200728-101715-38328.log 
su: ignore --preserve-environment, it's mutually exclusive to --login.
Error in reconcilePropertiesAndPrototype(name, slots, prototype, superClasses,  : 
  no definition was found for superclass “SingleCellExperiment” in the specification of class “SingCellaR”
Calls: runApp ... makeClassRepresentation -> reconcilePropertiesAndPrototype
Execution halted
```

**Comment by supatt-lab** [comment]
Hi,

I am not sure about this error. Did you install "SingleCellExperiment" and all other requirements in your standalone R?

Supat

**Comment by splaisan** [comment]
Hi Supat,

Yes, I just reinstalled them all with BiocManager to verify and still get the error.
All my R libraries are located together so the shiny server sees the same libs as ly RStudio.
What is weird is that your manual method works in RStudio by clicking on 'run App' within server.R

```
library(shiny)
runApp()
```

while running your app from a web-browser using the shiny server side by URL fails (also using localhost on the server itself).

I have many other shiny apps on that server which all run well.

I can use it all right but would have liked to share it with colleagues who do not know R and would benefit from using the web-side.

Could you use your App on the shiny server side of a unix server?

Could it be that the local manual mode sees the 3 sourced files while the shiny server for some reason does not get them loaded and therefore misses all the content?

=> the doc seems to say your config should work though!

```
In an R script in the R/ subdirectory
You can create a separate R script (.R file) for the module in the R/ subdirectory of your application. 
It will automatically be sourced (as of Shiny 1.5.0) when the application is loaded.
```

**Comment by splaisan** [comment]
Hi Supat,
I found it!
It was simply due to the fact you did not define the main class _"SingleCellExperiment"_ on top of `SingleCellClasses.R`

adding `setClass("SingleCellExperiment")` on top of that file fixed it

I can now launch the app on lmy Shinty server.

Best
S

**Comment by supatt-lab** [comment]
Great Thanks!
Best,
Supat
