### ISSUE TITLE
Data download link broken

### ISSUE THREAD

**Issue by winni2k** [supatt-lab/SingCellaR-myelofibrosis#3]
I get a 404 error when trying to download the data for this app (http://sara.molbiol.ox.ac.uk/public/supatt/shared_data/projects.tar.gz). Perhaps a more reliable place to host this data is on Zenodo?

**Comment by supatt-lab** [comment]
Sorry for the broken link. It is now back!.
Best,
Supat

**Comment by winni2k** [comment]
Thanks!
