### ISSUE TITLE
Projects data does not contain Gene expression data

### ISSUE THREAD

**Issue by nasjr08** [supatt-lab/SingCellaR-myelofibrosis#4]
I have been attempting to investigate the shinyapp from described in this Github project.

However, even though I was successfully able to follow the steps and run the app, it does not appear that there is any gene expression data stored in the SingleCellaR object (The data I am instructed to donwload). I do see the UMAP plot on the app and the table of marker genes, but not the gene expression data.

Further, whenI investigate the data myself in R (when I load in Psaila_et_al.rdata), I don't quite see the gene expression matrix in any of the slots held in the Psaila_et_al Robject. Can you please clarify why this is the case, and how I can retrieve the raw or normalised data/counts?

Many thanks,
Naseer Basma

**Comment by supatt-lab** [comment]
Hi Naseer Basma,

Apologies for my slow response. Please install the SingCellaR package https://github.com/supatt-lab/SingCellaR and follow the R script shown below. 

I hope this helps!. Let me know if you still cannot get the gene expression matrix.

BW,
Supat

library(SingCellaR)

my_obj<-local(get(load("Psaila_et_al.rdata")))
##########get UMI count###########
my_umi<-get_umi_count(my_obj)
##########get cell information####
cell_info<-get_cells_annotation(my_obj)

plot_umap_label_by_clusters(my_obj,show_method = "merged_louvain")
plot_umap_label_by_genes(my_obj,gene_list = c("PF4"))

**Comment by mollybwustl** [comment]
I'm trying this and it is not working at all :( Everything I try is getting the same error code. Only with get_umi_count, not with get_cells_annotation.
```
my_umi<-get_umi_count(my_obj)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘assay’ for signature ‘"SingCellaR_Int", "character"’
```
nothing is masking counts or assay in the original code, and I can't find an issue in the setClass() function in the R folders. Help!
